### ISSUE TITLE
The FastLED example does not work

### ISSUE THREAD

**Issue by TheGreyDiamond** [DaAwesomeP/dmxusb#11]
I'm trying to use this lib on an Arduino nano. But the FastLED example throws the following error: `C:\Users\XXXXXX\Documents\Arduino\libraries\DMXUSB\src/DMXUSB.h:26:29: fatal error: elapsedMillis.h: No such file or directory` What am I doing wrong?

**Comment by clementGdev** [comment]
Hello @TheGreyDiamond ,
I encountered the same issue and the fix is quite simple :
you need to install the elapsedMillis library (Sketch > Tools > Include Library > Manage Libraries and search for elapsedMillis).

It worked for me, I hope it will help !

Clement

**Comment by DaAwesomeP** [comment]
Yup, that's it! You need `elapsedMillis`. Thanks @clementGdev .

**Comment by DaAwesomeP** [comment]
I have released [v0.0.4](https://github.com/DaAwesomeP/dmxusb/releases/tag/v0.0.4) which adds that the dependency is required for non-Teensy boards (see commit https://github.com/DaAwesomeP/dmxusb/commit/303048926e0c202c000d77c321a5a4ec15f0103f).
