### ISSUE TITLE
Baudrate

### ISSUE THREAD

**Issue by nwebsta** [DaAwesomeP/dmxusb#12]
Hello,
im using OLA on a RPI3 and your programm on an arduino mega. Everything works fine when the baudrate is set to 115200. Any other value will not work. Do you know what causes the problem?

Niclas

**Comment by DaAwesomeP** [comment]
Have you tried explicitly changing the board rate of the port on the Pi? I believe you can use the `stty` command.

I don't know that the Teensy notifies/negotiates its baudrate. What other values are you trying? Does it work with a lower rate? I have only tried the very high baud rates on Teensy boards. The Arduinos has higher serial error rates at higher baud rates than the Teensies.

**Comment by DaAwesomeP** [comment]
OK, I was wrong. The Teensy [always uses its maximum baudrate on USB](https://forum.pjrc.com/threads/18852-Teensy-3-0-to-PC-communication-via-USB-serial-(-gt-256000-baud)?p=23705&viewfull=1#post23705).

I'll pull out my Arduino Mega in a bit and do some testing.

**Comment by nwebsta** [comment]
I also tried lower baudrates like 9600 but it doesnt work.

**Comment by DaAwesomeP** [comment]
Did you try changing the serial port speed on the Pi with `stty`? If you have any experience with bytecode/sending hex messages over serial, you can see if the Arduino responds to commands without OLA. If it does, then it may be an OLA issue. You can also try OLA on your computer.

**Comment by DaAwesomeP** [comment]
Closing for now—please feel free to reopen if you have more opportunities to debug!
