### ISSUE TITLE
Difference between two examples

### ISSUE THREAD

**Issue by paoloros97** [DaAwesomeP/dmxusb#16]
Hello,

What's the difference between the "DMXUSB_Simple" and the "DMXUSB_DmxSimple" examples?

Thank you in advance :)

PS: I'm looking for an emulator USB to DMX to be used with freestyler

**Comment by DaAwesomeP** [comment]
Hi there! I'm happy to help!

Take a look at the last line of the callback function in each example. In `DMXUSB_Simple`, the callback dim am LED on the first universe ane first channel:

https://github.com/DaAwesomeP/dmxusb/blob/70d4ae3dfafdc91a9b7d6e4a9c4b730d281e0667/examples/DMXUSB_Simple/DMXUSB_Simple.ino#L37

In `DMXUSB_DmxSimple`, the callback sends thr entire first universe into the [DmxSimple library](https://github.com/PaulStoffregen/DmxSimple), which can output a real DMX signal (with the right hardware):

https://github.com/DaAwesomeP/dmxusb/blob/70d4ae3dfafdc91a9b7d6e4a9c4b730d281e0667/examples/DMXUSB_DmxSimple/DMXUSB_DmxSimple.ino#L52

Hopefully that clears that up! Let me know if you have any more questions

I'm not familiar with FreeStyler, but it looks like a DMX controller program similar to QLC+. Assuming it can see an arbitrary Enttec device on any serial port (which this emulates), then it should work. If not, then you may need an FTDI adapter or to use [OLA](https://www.openlighting.org/ola/) as an adapter.

Wbat is your intended output? Are you connecting real DMX fixtures or your own electronics?

**Comment by DaAwesomeP** [comment]
@paoloros97 please let me know if I can be of any further assistance!

**Comment by DaAwesomeP** [comment]
Closing due to no response.

**Comment by tonyxforce** [comment]
> Wbat is your intended output? Are you connecting real DMX fixtures or your own electronics?

Can i use this firmware to use an arduino leonardo with a SN75176BP chip to control real dmx fictures through usb?

**Comment by DaAwesomeP** [comment]
Hey @tonyxforce,

Yes, the `DMXUSB_DmxSimple` example is probably where you want to start. I would recommend looking at the `DmxSimple` examples first and get it working before you add in DMXUSB.
