### ISSUE TITLE
ESP32C3

### ISSUE THREAD

**Issue by Shuptuu** [DaAwesomeP/dmxusb#20]
Hi,
I tried to make dmxusb running on a Seeed Xiao ESP32C3 but didn't succeed...
Compilation is ok, but can't receive any data.
Tried with Chataigne Software - dmx type Enttec DMX Pro.
And DMX Control V3: no Enttec DMX Pro device detected.
It's quite difficult to debug as long as you loose access to the serial monitor.
Any reason which could explain why it doesn't work on this board?

**Comment by DaAwesomeP** [comment]
Hi @Shuptuu,

Depending on the software you are trying to use, you may need a FTDI serial interface or a microcontroller with one built in (must be specifically FTDI). See https://github.com/DaAwesomeP/dmxusb/issues/17#issuecomment-1205869441 and https://github.com/DaAwesomeP/dmxusb/issues/18#issuecomment-1276287214

**Comment by Shuptuu** [comment]
Thanks for your answer. It means it can't work with this board through it's usb uart...
Would have been cool, but Oh well...
Thanks anyway

**Comment by DaAwesomeP** [comment]
@Shuptuu feel free to open an issue with Chataigne (also open source) to support generic serial ports!
