### ISSUE TITLE
Not working with Arduino uno r3

### ISSUE THREAD

**Issue by Samuel782** [DaAwesomeP/dmxusb#21]
Hi, I am trying to make a dmx Usb converter, I loaded the example sketches on my arduino uno r3, but my mac seems not to recognize any usb-dmx peripheral, am I doing something wrong?

**Comment by avicarpio** [comment]
Same on Arduino Mega 2560

**Comment by DaAwesomeP** [comment]
Hey, sorry I missed this!

Depending on the software you are trying to use, you may need a FTDI serial interface or a microcontroller with one built in (must be specifically FTDI). See https://github.com/DaAwesomeP/dmxusb/issues/17#issuecomment-1205869441 and https://github.com/DaAwesomeP/dmxusb/issues/18#issuecomment-1276287214
