### ISSUE TITLE
Out of bound memory

### ISSUE THREAD

**Issue by Duccan** [DaAwesomeP/dmxusb#9]
In [DMXUSB.cpp](https://github.com/DaAwesomeP/dmxusb/blob/master/src/DMXUSB.cpp) line 93, you are writing to your buffer out of range. When `_index` is zero, your writing to `_buffer` at index `(unsigned int) 0 - (unsigned int) 1` which equals to a max value of unsigned int `65535` (depends on target). If you want to omit the first bit, build a check for it to skip it.

**Comment by DaAwesomeP** [comment]
Hi @Duccan,
I'm surprised I didn't catch this myself! If you'd like to submit a pull and can test it on your own hardware, that is very welcome. I can try to release a fix in the next week or so.
